---
- name: Training Provision 
  hosts: all
  user: ubuntu
  sudo: True
  tasks:
  - name: update
    command: apt-get update

  - name: install all required deps
    apt: pkg={{ item }} state=installed
    with_items:
    - git
    - curl 
    - make 
    - python-pip
    - python-imaging
    - python-support
    - build-essential
    - libncurses5-dev
    - openssl
    - fop
    - xsltproc
    - unixodbc-dev
    - libc6-dev-i386
    - libssl-dev

  - name: grab erlang
    shell: wget http://erlang.org/download/otp_src_R15B01.tar.gz

  - name: unzip erlang
    shell: tar zxvf otp_src_R15B01.tar.gz

  - name: make erlang
    shell: cd otp_src_R15B01 && ./configure && make && make install

  - name: grab riak 1.4.7
    shell: wget -O /usr/src/riak-1.4.7.tar.gz http://s3.amazonaws.com/downloads.basho.com/riak/1.4/1.4.7/riak-1.4.7.tar.gz

  - name: grab git repo
    shell: cd /usr/src && git clone https://github.com/joeljacobson/ansible-devrel.git

  - name: install boto
    pip: name=boto state=latest

  - name: get tornado
    shell: wget https://github.com/downloads/liftoff/GateOne/python-tornado_2.4-1_all.deb

  - name: get gateone
    shell: wget https://github.com/downloads/liftoff/GateOne/gateone_1.1-1_all.deb

  - name: install packages
    shell: dpkg -i *.deb

  - name: install server.conf
    copy: src=server.conf dest=/opt/gateone/server.conf

  - name: make sure that the ansible_backup directory exists
    action: file path=/opt/gateone/logs state=directory

  - name: start gateone
    service: name=gateone state=started


